name: dyene
on:
  push: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - uses: actions/setup-node@v3
        with:
          node-version: v18.17.1
          cache: npm 

      - name: Install dependencies
        run: npm ci

      - name: Track main branch
        run: |
          git fetch origin main
          git branch --track main origin/main 

      - name: Build packages
        run: npx nx affected -t build

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - uses: actions/setup-node@v3
        with:
          node-version: v18.17.1
          cache: npm 

      - name: Install dependencies
        run: npm ci

      - name: Track main branch
        run: |
          git fetch origin main
          git branch --track main origin/main 

      - name: Component Test
        run: npx nx affected -t test:component

  component-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      - uses: actions/setup-node@v3
        with:
          node-version: v18.17.1
          cache: npm 

      - name: Install dependencies
        run: npm ci

      - name: Track main branch
        run: |
          git fetch origin main
          git branch --track main origin/main 

      - name: Component Test
        run: npx nx affected -t test:component
    