name: dyene
on:
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3 

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: v18.17.1
          cache: npm 

      - name: Install dependencies
        run: npm ci

      - name: Track main branch
        run: |
          git fetch origin main
          git branch --track main origin/main 

      - name: Build packages
        run: npx nx affected -t build
    